"""empty message

Revision ID: 178a6961a94f
Revises: 3c2927c02869
Create Date: 2020-10-19 13:03:02.836253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178a6961a94f'
down_revision = '3c2927c02869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todo_list', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'list_id')
    # ### end Alembic commands ###
